/**
 * 工作流版教程场景 — 对齐 docs/AI中台使用教程-工作流版.md
 * 零算力：只导航 / 高亮 / 展示 fixture，不提交真实任务
 */

import {
  COPYWRITING_LLM_ECONOMY,
  FIXED_SCENE_COSTS,
  GEO_ARTICLE_ECONOMY,
  SEEDANCE_SEGMENT_COST,
} from "@/lib/credit-pricing/registry"
import type { TutorialScenario, TutorialWorkflowId } from "@/lib/tutorial/types"
import { GEO_VIEWS } from "@/lib/geo/workspace"
import { VIDEO_VIEWS } from "@/lib/video/workspace"

const FC = {
  positioning: "/tutorial/flowcharts/01-positioning-content.png",
  dhOral: "/tutorial/flowcharts/02-digital-human.png",
  imageVideo: "/tutorial/flowcharts/03-image-video.png",
  mashup: "/tutorial/flowcharts/04-mashup-video.png",
  promo: "/tutorial/flowcharts/05-promo-video.png",
  geo: "/tutorial/flowcharts/06-geo-growth.png",
} as const

export const TUTORIAL_WORKFLOWS: TutorialScenario[] = [
  {
    id: "wf-prep",
    workflowId: "prep",
    kind: "prep",
    module: "dashboard",
    title: "开始前准备",
    description: "正式创作前完成登录、积分、资料与目标确认，避免生成后返工。",
    estimatedMinutes: 4,
    priority: "path",
    pathOrder: 0,
    targetView: "工作台",
    docSection: "一、开始前准备",
    applicableWhen: "第一次使用，或换账号 / 换业务线开新项目时。",
    goal: "确认账户可用、资料齐备、本次内容目标清晰",
    prepRequirements: ["已注册账号", "准备品牌/产品基础资料"],
    inputs: ["账户登录态", "业务资料", "内容目标"],
    outputs: ["可开始正式工作流"],
    finalOutcomes: ["积分充足", "资料与目标明确", "发布渠道已评估"],
    fixtureKey: "dashboard",
    steps: [
      {
        id: "prep-1",
        title: "登录并确认积分",
        body: "登录 AI 中台后，看右上角积分徽章。创作视频、GEO、定位都会扣积分，建议先确认余额充足。",
        action: { type: "navigate", view: "充值兑换" },
        highlightTarget: "nav-充值兑换",
        checklist: ["已登录", "已查看当前余额", "知道兑换入口在「充值兑换」"],
        tip: "教程里的「已保存示例」不扣积分；只有真实点击生成才会计费。",
      },
      {
        id: "prep-2",
        title: "准备业务资料",
        body: "整理个人、企业、产品或服务的基础事实：行业、客户、痛点、产品名、差异化优势。后续定位与 GEO 都依赖这些事实。",
        action: { type: "navigate", view: "工作台" },
        highlightTarget: "nav-工作台",
        checklist: ["有一句话业务描述", "有目标客户描述", "有可上传的介绍/手册（可选）"],
        warning: "业务事实、品牌名称、产品信息最终仍需人工确认，不要全盘信任 AI。",
      },
      {
        id: "prep-3",
        title: "明确本次内容目标",
        body: "想清楚：内容面向谁、解决什么问题、希望用户采取什么行动（关注、到店、询价、下单）。",
        checklist: ["写清受众", "写清要解决的问题", "写清期望行动（CTA）"],
        tip: "目标越具体，文案选题和视频分镜越不容易跑偏。",
      },
      {
        id: "prep-4",
        title: "发布渠道（可选）",
        body: "若需要一键分发，需先完成目标平台账号绑定。当前部分分发能力仍在完善中；也可先下载成片再人工发布。",
        action: { type: "navigate", view: "设置" },
        highlightTarget: "nav-设置",
        checklist: ["已决定先下载还是走分发", "若分发：平台授权状态已确认"],
        warning: "未挂载的「一键分发」入口不要强行寻找；成片可在「历史记录」下载。",
        expectedOutcome: "准备完成，可以进入定位或视频工作流。",
      },
    ],
  },
  {
    id: "wf-positioning-content",
    workflowId: "positioning-content",
    kind: "workflow",
    module: "ip-positioning",
    title: "账号定位与内容方向",
    description: "从业务资料到定位报告，再落到长期内容方向与可拍的口播文案。",
    estimatedMinutes: 10,
    priority: "path",
    pathOrder: 1,
    targetView: "身份定位",
    docSection: "二、账号定位与内容方向工作流",
    flowchart: FC.positioning,
    applicableWhen: "个人 IP 刚起步、企业账号定位不清，或不知道该长期发什么。",
    goal: "得到清晰定位 + 3～5 个长期方向 + 可进入视频的口播稿",
    prepRequirements: ["行业与业务描述", "目标客户与痛点", "可选公司介绍/手册"],
    inputs: ["定位问卷", "补充资料", "选题诉求"],
    outputs: ["定位报告", "内容方向", "选题列表", "口播文案"],
    finalOutcomes: [
      "一份清晰的个人或企业定位",
      "3～5 个长期内容方向",
      "一批可持续创作的选题",
      "可直接进入视频制作的口播文案",
    ],
    nextModules: ["copywriting", "dh-video-v2"],
    fixtureKey: "ip-positioning",
    creditHints: [
      {
        scene: "ai_ip_positioning",
        costLabel: `${FIXED_SCENE_COSTS.ai_ip_positioning} 积分`,
        note: "真实生成定位报告",
      },
      {
        scene: "copywriting_llm",
        costLabel: `${COPYWRITING_LLM_ECONOMY}–15 积分/次`,
        note: "真实文案对话",
      },
    ],
    steps: [
      {
        id: "pc-0",
        title: "先看完整流程图",
        body: "本工作流：业务资料 → 身份定位 →（可选竞品/爆款洞察）→ 内容方向 → 文案选题与口播。",
        flowchart: FC.positioning,
        action: { type: "navigate", view: "身份定位" },
        highlightTarget: "nav-身份定位",
        checklist: ["理解最终要产出定位与口播，而不是只填一张表"],
      },
      {
        id: "pc-1",
        title: "填写身份定位资料",
        body: "进入「身份定位」，填写行业、主要业务、目标客户、客户痛点、核心产品和差异化优势。已有公司介绍、产品手册可作补充资料上传。",
        action: { type: "navigate", view: "身份定位" },
        highlightTarget: "ip-positioning-wizard",
        checklist: [
          "行业与业务写具体（避免只写「服务业」）",
          "目标客户有人群标签",
          "差异化优势能用一句话说清",
        ],
        tip: "可先点「试试示例」看表单长什么样；真实提交才会扣积分。",
      },
      {
        id: "pc-2",
        title: "生成并验收定位结果",
        body: "让 AI 生成定位后，重点检查：我是谁、服务谁、解决什么问题、为什么选择我。过于宽泛就补充客户类型、场景和案例后重跑。",
        action: { type: "showDemo", fixtureKey: "ip-positioning" },
        highlightTarget: "tutorial-demo-panel",
        checklist: [
          "oneLiner 能对外介绍自己",
          "受众与避坑方向合理",
          "平台打法与内容支柱可执行",
        ],
        warning: "教程面板是静态示例报告；真实生成约 20 积分。",
        expectedOutcome: "一份可保存的定位报告",
      },
      {
        id: "pc-3",
        title: "竞品 / 爆款 / 诊断（可选）",
        body: "文档建议用竞品扫描、爆款分析、账号诊断加深洞察。若侧栏暂无独立入口，可先用定位报告里的平台打法与内容支柱代替，或后续版本再开放。",
        checklist: ["已读定位报告中的平台与内容建议", "记下 1～2 个想对标的内容形式"],
        tip: "未开放的功能不要卡住主流程——先定 3～5 个长期内容方向即可往下走。",
      },
      {
        id: "pc-4",
        title: "定 3～5 个长期内容方向",
        body: "例如：行业知识、客户避坑、产品使用、真实案例、经营观点。方向要既能服务客户，又能体现你的优势。",
        checklist: ["写出 3～5 个方向名词", "每个方向能想到至少 2 个选题"],
      },
      {
        id: "pc-5",
        title: "文案创作：批量选题",
        body: "进入「文案创作」，告诉 AI 你的行业身份与内容方向，让它批量生成选题。",
        action: { type: "navigate", view: "文案创作" },
        highlightTarget: "copywriting-workspace",
        checklist: ["已说明身份与目标客户", "已要求 10 个左右选题", "选题能引发关注且贴业务"],
        tip: "示例口令：我是做烟酒生意的老板，目标客户有商务宴请和送礼需求。请围绕选购避坑、真假辨别、商务送礼，创作 10 个短视频选题。",
      },
      {
        id: "pc-6",
        title: "选定题目并写口播",
        body: "从候选选题中挑一个：既符合客户需求，又能体现业务优势。再让 AI 写口播文案，核对事实与案例后即可进入视频工作流。",
        action: { type: "showDemo", fixtureKey: "copywriting" },
        highlightTarget: "tutorial-demo-panel",
        checklist: [
          "文案有清晰开头 / 核心观点 / 具体内容 / 结尾引导",
          "事实与品牌名已人工校对",
          "可一键跳转对应视频创作",
        ],
        expectedOutcome: "可直接拍的口播文案",
      },
    ],
  },
  {
    id: "wf-dh-oral",
    workflowId: "dh-oral",
    kind: "workflow",
    module: "dh-video-v2",
    title: "数字人口播视频创作",
    description: "原创选题或文案提取 → 素材 → 分镜 → 成片 → 历史记录。",
    estimatedMinutes: 12,
    priority: "path",
    pathOrder: 2,
    targetView: VIDEO_VIEWS.DH_VIDEO_V2,
    docSection: "三、数字人口播视频创作工作流",
    flowchart: FC.dhOral,
    applicableWhen: "知识分享、老板 IP、企业介绍、产品讲解、行业观点口播。",
    goal: "产出一条完整数字人口播视频与封面",
    prepRequirements: ["口播文案", "清晰人像参考图", "可选 2～15 秒参考音频"],
    inputs: ["形象图", "音色", "口播稿", "创意描述"],
    outputs: ["分镜脚本", "成片", "封面"],
    finalOutcomes: ["一条完整数字人口播视频", "一张视频封面", "可复用的选题、口播与分镜提示词"],
    nextModules: ["video-history"],
    fixtureKey: "dh-video-v2",
    creditHints: [
      {
        scene: "dh_v2_plan_script",
        costLabel: `${FIXED_SCENE_COSTS.dh_v2_plan_script} 积分`,
        note: "AI 分镜",
      },
      {
        scene: "dh_v2_video_segment",
        costLabel: `${SEEDANCE_SEGMENT_COST} 积分/约 15s 段`,
        note: "成片按段计费",
      },
    ],
    steps: [
      {
        id: "dh-0",
        title: "总览生产线",
        body: "两条进料：原创选题文案，或提取已有视频再改写；汇入数字人口播后分镜、生成、下载。",
        flowchart: FC.dhOral,
        action: { type: "navigate", view: VIDEO_VIEWS.DH_VIDEO_V2 },
        highlightTarget: "nav-数字人口播视频（新）",
        checklist: ["知道口播内容从哪来", "知道成片在历史记录可回看"],
      },
      {
        id: "dh-1",
        title: "准备口播内容",
        body: "方式一：文案创作批量选题再写口播。方式二：文案提取粘贴链接，校对后用 AI 改写，避免照搬。",
        action: { type: "navigate", view: "文案创作" },
        highlightTarget: "nav-文案创作",
        checklist: [
          "文案口语化",
          "有清晰开头、核心观点、具体内容、结尾引导",
          "品牌名与数字已校对",
        ],
        tip: "也可先去「文案提取」看示例结果，再回到本流程。",
      },
      {
        id: "dh-2",
        title: "准备数字人素材",
        body: "准备清晰形象图：主体完整、面部清楚、无遮挡。克隆音色用 2～15 秒单人清晰音频，避免 BGM 与多人说话。",
        action: { type: "navigate", view: VIDEO_VIEWS.DH_VIDEO_V2 },
        highlightTarget: "dh-v2-compose",
        checklist: ["形象图符合账号调性", "音频时长与清晰度合格（若需克隆）"],
        warning: "素材不合格会导致口型或画质问题，先检查再提交。",
      },
      {
        id: "dh-3",
        title: "生成分镜脚本",
        body: "上传形象与音频，粘贴最终口播稿。系统按文案长度估算时长并拆成约 15 秒一段的分镜。",
        action: { type: "showDemo", fixtureKey: "dh-video-v2" },
        highlightTarget: "tutorial-demo-panel",
        checklist: ["已理解分段逻辑", "示例分镜里每段有台词与镜头描述"],
        tip: "教程示例已含分镜；真实「生成分镜」约 20 积分。",
      },
      {
        id: "dh-4",
        title: "优化分镜提示词",
        body: "不要立刻成片。逐段检查人物、场景、动作、镜头与文案是否一致；提示词写清「谁、在哪里、做什么、镜头如何」。",
        highlightTarget: "dh-v2-script-plan",
        checklist: [
          "每段 dialogue 与口播一致",
          "提示词具体而非「高级感」",
          "删除或改写不符预期的段",
        ],
        warning: "模糊提示词最容易导致人物漂移或场景跑偏。",
      },
      {
        id: "dh-5",
        title: "生成并检查视频",
        body: "确认分镜后提交。可查看各段状态；单段失败可单独重试。合成后检查人物一致性、口型、跳转、字幕与声音。",
        checklist: ["预览完整成片", "失败段已处理或知悉重试入口"],
        tip: "演示模式会拦截真实提交；请用「查看已保存示例」看成片形态。",
      },
      {
        id: "dh-6",
        title: "下载或准备发布",
        body: "下载视频与封面。任务保留在「历史记录」。一键分发若未开放，先本地保存再人工发平台。",
        action: { type: "navigate", view: VIDEO_VIEWS.HISTORY },
        highlightTarget: "nav-历史记录",
        checklist: ["已找到历史记录中的成片入口", "已计划标题与描述（若发布）"],
        expectedOutcome: "成片可下载复用",
      },
    ],
  },
  {
    id: "wf-image-video",
    workflowId: "image-video",
    kind: "workflow",
    module: "image-video",
    title: "图文视频创作",
    description: "口播文案 + 多图 + 参考音色 → 图文口播成片。",
    estimatedMinutes: 8,
    priority: "p1",
    pathOrder: 3,
    targetView: VIDEO_VIEWS.IMAGE_VIDEO,
    docSection: "四、图文视频创作工作流",
    flowchart: FC.imageVideo,
    applicableWhen: "案例展示、产品介绍、知识清单、门店展示，不需要固定数字人出镜。",
    goal: "产出一条图文口播视频",
    prepRequirements: ["口播文案", "至少 7 张顺序图", "参考音色"],
    inputs: ["图片序列", "音色", "旁白文案"],
    outputs: ["图文成片", "可发布文案"],
    finalOutcomes: ["一条图文口播视频", "按文案顺序整理的图片素材", "可直接发布的标题描述"],
    fixtureKey: "image-video",
    creditHints: [
      {
        scene: "video_image_to_video",
        costLabel: `${FIXED_SCENE_COSTS.video_image_to_video} 积分 + 克隆`,
        note: "真实提交图文视频",
      },
    ],
    steps: [
      {
        id: "iv-0",
        title: "总览图文流程",
        body: "文案 → 按段落配图 → 上传音色与文案 → 合成预览 → 下载/发布。",
        flowchart: FC.imageVideo,
        action: { type: "navigate", view: VIDEO_VIEWS.IMAGE_VIDEO },
        highlightTarget: "nav-图文视频",
        checklist: ["确认不需要数字人出镜"],
      },
      {
        id: "iv-1",
        title: "准备口播文案",
        body: "用文案创作生成选题与旁白，或文案提取后改写。",
        action: { type: "navigate", view: "文案创作" },
        highlightTarget: "nav-文案创作",
        checklist: ["文案段落可对应图片", "口语顺畅"],
      },
      {
        id: "iv-2",
        title: "按文案准备图片",
        body: "每张图对应一段内容，顺序与口播逻辑一致；统一比例与风格，避免清晰度差过大。",
        checklist: ["建议 ≥7 张", "顺序已按旁白排好", "风格统一"],
        tip: "图比文案少时，先拆文案或补图，不要硬提交。",
      },
      {
        id: "iv-3",
        title: "进入图文视频并上传",
        body: "上传图片、参考音色和口播文案，可开关字幕与 BGM。",
        action: { type: "navigate", view: VIDEO_VIEWS.IMAGE_VIDEO },
        highlightTarget: "image-video-workflow",
        checklist: ["三要素齐全：图 / 声 / 文", "图片顺序正确"],
      },
      {
        id: "iv-4",
        title: "提交与预览",
        body: "系统完成音色克隆、配音、字幕、BGM、转场与合成。预览时检查顺序、断句、配音与切换。",
        action: { type: "showDemo", fixtureKey: "image-video" },
        checklist: ["预览通过或知悉失败时优先查素材数量/格式/大小"],
        warning: "演示模式不真实提交。",
      },
      {
        id: "iv-5",
        title: "下载与发布准备",
        body: "下载成片；需要发布时整理标题描述。分发未开放则人工上传平台。",
        action: { type: "navigate", view: VIDEO_VIEWS.HISTORY },
        highlightTarget: "nav-历史记录",
        expectedOutcome: "图文成片可交付",
      },
    ],
  },
  {
    id: "wf-mashup",
    workflowId: "mashup",
    kind: "workflow",
    module: "mashup",
    title: "视频混剪创作",
    description: "已有实拍素材 + 口播文案 → 混剪成片。",
    estimatedMinutes: 9,
    priority: "p1",
    pathOrder: 4,
    targetView: VIDEO_VIEWS.MASHUP,
    docSection: "五、视频混剪创作工作流",
    flowchart: FC.mashup,
    applicableWhen: "已有门店、产品、活动、施工、服务过程等视频素材。",
    goal: "快速重剪成口播短视频",
    prepRequirements: ["≥5 段相关视频", "口播文案", "参考音色", "可选封面图"],
    inputs: ["视频素材", "音色", "文案", "封面图可选"],
    outputs: ["混剪成片", "可选封面"],
    finalOutcomes: ["一条混剪成片", "可选封面", "可复用的原始素材库"],
    fixtureKey: "mashup",
    creditHints: [
      {
        scene: "video_mashup",
        costLabel: `${FIXED_SCENE_COSTS.video_mashup} 积分 + 克隆`,
        note: "真实提交混剪",
      },
    ],
    steps: [
      {
        id: "mv-0",
        title: "总览混剪流程",
        body: "文案准备 → 筛选素材 → 音色/封面 → 上传提交 → 预览 → 下载。",
        flowchart: FC.mashup,
        action: { type: "navigate", view: VIDEO_VIEWS.MASHUP },
        highlightTarget: "nav-视频混剪",
        checklist: ["确认手头有多段可用实拍"],
      },
      {
        id: "mv-1",
        title: "准备口播文案",
        body: "AI 创作或提取改写，保证与画面内容可对应。",
        action: { type: "navigate", view: "文案创作" },
        checklist: ["文案能对应实拍场景"],
      },
      {
        id: "mv-2",
        title: "筛选视频素材",
        body: "覆盖不同场景与景别；删掉无关、模糊、重复片段。",
        checklist: ["建议 ≥5 段", "已去废片"],
      },
      {
        id: "mv-3",
        title: "音色与封面",
        body: "准备清晰参考音色；需要封面时另备一张参考图，不需要可跳过。",
        checklist: ["音色合格", "封面策略已定"],
      },
      {
        id: "mv-4",
        title: "上传并提交",
        body: "进入「视频混剪」，上传视频、音色、文案与可选封面后提交。系统配音并套剪辑模板。",
        action: { type: "navigate", view: VIDEO_VIEWS.MASHUP },
        highlightTarget: "mashup-workflow",
        checklist: ["素材完整再点提交"],
      },
      {
        id: "mv-5",
        title: "预览检查",
        body: "检查素材与口播是否对应、节奏、字幕、BGM 是否压过人声。",
        action: { type: "showDemo", fixtureKey: "mashup" },
        checklist: ["预览清单过一遍"],
      },
      {
        id: "mv-6",
        title: "下载与复用",
        body: "下载视频与封面；原始素材可继续用于下一条混剪。",
        action: { type: "navigate", view: VIDEO_VIEWS.HISTORY },
        expectedOutcome: "混剪成片可交付",
      },
    ],
  },
  {
    id: "wf-promo",
    workflowId: "promo",
    kind: "workflow",
    module: "promo-video",
    title: "产品宣传视频创作",
    description: "产品卖点 → 宣传文案 → 分镜图 → 提示词 → 成片。",
    estimatedMinutes: 10,
    priority: "p1",
    pathOrder: 5,
    targetView: VIDEO_VIEWS.PROMO,
    docSection: "六、产品宣传视频创作工作流",
    flowchart: FC.promo,
    applicableWhen: "新品展示、卖点介绍、品牌宣传、电商推广、活动预热。",
    goal: "产出一条产品宣传短片与可复用分镜",
    prepRequirements: ["产品名与卖点", "目标客户与行动号召", "可选产品图与音色"],
    inputs: ["产品描述", "宣传文案", "产品图或文生图描述"],
    outputs: ["分镜帧", "运镜提示词", "宣传成片"],
    finalOutcomes: ["一条产品宣传视频", "一组可复用分镜图", "宣传文案与视频提示词"],
    fixtureKey: "promo-video",
    creditHints: [
      {
        scene: "promo_storyboard",
        costLabel: `${FIXED_SCENE_COSTS.promo_storyboard} 积分`,
        note: "分镜",
      },
      {
        scene: "promo_segment",
        costLabel: `${SEEDANCE_SEGMENT_COST} 积分/约 15s`,
        note: "成片按段",
      },
    ],
    steps: [
      {
        id: "pv-0",
        title: "总览宣传片流程",
        body: "图生图与文生图两种模式汇入同一条宣传视频生产线。",
        flowchart: FC.promo,
        action: { type: "navigate", view: VIDEO_VIEWS.PROMO },
        highlightTarget: "nav-宣传视频",
        checklist: ["已整理产品核心卖点（一条短视频只打一个卖点）"],
      },
      {
        id: "pv-1",
        title: "整理产品信息",
        body: "产品名称、目标客户、核心卖点、使用场景、差异化、希望用户行动。",
        checklist: ["信息可写成一段产品描述"],
      },
      {
        id: "pv-2",
        title: "文案：角度与成稿",
        body: "文案创作先出多个宣传角度，再选一个方向写完整宣传文案，避免信息堆砌。",
        action: { type: "navigate", view: "文案创作" },
        highlightTarget: "nav-文案创作",
        checklist: ["只有一个核心卖点", "文案长度适配 15～60 秒"],
      },
      {
        id: "pv-3",
        title: "选择生成模式并填表",
        body: "图生图需清晰产品图；文生图用画面描述。填写场景描述、文案，设置宫格、分辨率等参数。",
        action: { type: "navigate", view: VIDEO_VIEWS.PROMO },
        highlightTarget: "promo-video-workflow",
        checklist: ["模式选对", "参数符合目标平台"],
      },
      {
        id: "pv-4",
        title: "生成并筛选分镜",
        body: "逐张检查产品外观、场景、动作与品牌调性；不准的提示词先改再生成视频。",
        action: { type: "showDemo", fixtureKey: "promo-video" },
        checklist: ["已选出可用分镜帧"],
      },
      {
        id: "pv-5",
        title: "优化视频提示词并成片",
        body: "写清镜头运动、氛围与转场；提交后并发生成约 15 秒片段再合成。",
        checklist: ["提示词具体", "预览产品清晰、卖点准确、分镜连贯"],
        warning: "演示模式拦截真实生成。",
      },
      {
        id: "pv-6",
        title: "下载交付",
        body: "确认后下载；需要时再人工发布到电商或短视频平台。",
        action: { type: "navigate", view: VIDEO_VIEWS.HISTORY },
        expectedOutcome: "宣传片可投放",
      },
    ],
  },
  {
    id: "wf-geo-growth",
    workflowId: "geo-growth",
    kind: "workflow",
    module: "geo-knowledge",
    title: "GEO 内容增长",
    description: "企业知识库 → 两周矩阵 → 深度文章 → 评分优化 → 导出。",
    estimatedMinutes: 12,
    priority: "path",
    pathOrder: 6,
    targetView: GEO_VIEWS.KNOWLEDGE_BASE,
    docSection: "七、GEO 内容增长工作流",
    flowchart: FC.geo,
    applicableWhen: "希望持续生产企业内容，并提升被生成式 AI 准确理解与引用的机会。",
    goal: "建立可复用知识库并产出经 GEO 优化的文章",
    prepRequirements: ["企业事实资料", "产品/案例/FAQ 文档"],
    inputs: ["企业实体", "文档", "平台与 Skill"],
    outputs: ["GEO Skill", "内容矩阵", "评分文章", "Markdown 导出"],
    finalOutcomes: [
      "可复用的企业知识库与 GEO Skill",
      "一份两周内容矩阵",
      "多篇经 GEO 评分优化的深度文章",
    ],
    fixtureKey: "geo-knowledge",
    creditHints: [
      {
        scene: "geo_skill_gen",
        costLabel: `${FIXED_SCENE_COSTS.geo_skill_gen} 积分`,
        note: "生成 Skill",
      },
      {
        scene: "geo_matrix_gen",
        costLabel: `${FIXED_SCENE_COSTS.geo_matrix_gen} 积分`,
        note: "生成矩阵",
      },
      {
        scene: "geo_article",
        costLabel: `${GEO_ARTICLE_ECONOMY}–30 积分/篇`,
        note: "文章按模型计费",
      },
    ],
    steps: [
      {
        id: "geo-0",
        title: "总览 GEO 增长闭环",
        body: "知识库夯实事实 → 矩阵规划选题 → 深度文章 → 评分优化 → 导出（一键分发即将开放）。",
        flowchart: FC.geo,
        action: { type: "navigate", view: GEO_VIEWS.KNOWLEDGE_BASE },
        highlightTarget: "nav-企业知识库搭建",
        checklist: ["理解 GEO = 生成式引擎优化"],
      },
      {
        id: "geo-1",
        title: "建立企业知识库",
        body: "填写企业名称、品牌、业务、产品、目标用户与优势；上传介绍/手册/案例/FAQ，解析成功后生成 GEO Skill，并人工核对事实。",
        action: { type: "showDemo", fixtureKey: "geo-knowledge" },
        highlightTarget: "geo-knowledge-view",
        checklist: ["文档已解析", "Skill 事实已核对", "可设为默认 Skill"],
        warning: "错误事实进 Skill 会污染后续矩阵与文章。",
      },
      {
        id: "geo-2",
        title: "规划内容矩阵",
        body: "新建项目，选平台，填写业务与内容目标，引用企业知识库后生成两周矩阵；删改重复或偏离的选题。",
        action: { type: "navigate", view: GEO_VIEWS.CONTENT_MATRIX },
        highlightTarget: "geo-matrix-view",
        checklist: ["项目已建", "平台与 Skill 已选", "格子选题可执行"],
      },
      {
        id: "geo-2b",
        title: "阅读示例矩阵",
        body: "查看静态两周格子：标题、GEO 意图与方向如何排布。",
        action: { type: "showDemo", fixtureKey: "geo-matrix" },
        highlightTarget: "geo-matrix-view",
        checklist: ["能读懂 geoIntent（对比/教程/FAQ 等）"],
      },
      {
        id: "geo-3",
        title: "创作深度文章",
        body: "从矩阵选题或手输主题，选平台与知识库生成初稿；人工检查标题、事实、产品与案例。",
        action: { type: "navigate", view: GEO_VIEWS.ARTICLE_EDITOR },
        highlightTarget: "geo-article-view",
        checklist: ["初稿事实已校对"],
      },
      {
        id: "geo-4",
        title: "GEO 评分与优化",
        body: "用评分检查语义清晰度、对话语气、证据密度与结构化 FAQ；按建议补概念、数据、案例与问答，再评分。",
        action: { type: "showDemo", fixtureKey: "geo-article" },
        highlightTarget: "geo-article-view",
        checklist: ["结构有标题层级", "含可引用的事实块", "含 FAQ"],
        tip: "示例文章展示了「结论先行 + 可执行动作 + FAQ」结构。",
      },
      {
        id: "geo-5",
        title: "导出内容",
        body: "达标后导出 Markdown，用于官网、公众号等。GEO 一键分发标记为即将开放，现阶段导出后人工发布。",
        checklist: ["已导出或知悉导出入口", "不依赖未上线的一键分发"],
        expectedOutcome: "可发布的 GEO 文章",
      },
    ],
  },
  {
    id: "wf-finish-publish",
    workflowId: "finish-publish",
    kind: "workflow",
    module: "video-history",
    title: "成品管理与发布建议",
    description: "历史记录归档、资料保留与发布前检查清单。",
    estimatedMinutes: 4,
    priority: "p2",
    pathOrder: 7,
    targetView: VIDEO_VIEWS.HISTORY,
    docSection: "八、成品管理与发布建议",
    applicableWhen: "视频或文章已生成，准备下载、归档或对外发布。",
    goal: "成片可找回、资料可复盘、发布前检查完整",
    inputs: ["已生成任务"],
    outputs: ["本地下载", "发布清单"],
    finalOutcomes: ["原始成片与封面已保存", "选题到成片资料齐全", "发布检查完成"],
    fixtureKey: "video-history",
    steps: [
      {
        id: "fp-1",
        title: "在历史记录检查成片",
        body: "先在历史记录预览并下载原始成片与封面，不要只保留平台压缩版。",
        action: { type: "navigate", view: VIDEO_VIEWS.HISTORY },
        highlightTarget: "nav-历史记录",
        checklist: ["已下载视频", "已下载或生成封面"],
      },
      {
        id: "fp-2",
        title: "发布前绑定与确认",
        body: "一键分发前需完成平台绑定并确认浏览器登录。若分发入口未开放，用下载文件人工发布。遇手机验证需在弹出窗口人工完成。",
        checklist: ["平台账号策略已定", "标题与描述已准备"],
        warning: "不要把教程示例当成真实账号状态。",
      },
      {
        id: "fp-3",
        title: "保留复盘资料",
        body: "建议每条内容保留：原始选题、最终文案、素材、分镜提示词、成片、封面、发布文案，方便二次创作。",
        action: { type: "showDemo", fixtureKey: "video-history" },
        checklist: ["资料清单已建立习惯"],
        expectedOutcome: "成品管理闭环完成",
      },
    ],
  },
]

export function listWorkflowScenarios(): TutorialScenario[] {
  return [...TUTORIAL_WORKFLOWS].sort((a, b) => (a.pathOrder ?? 99) - (b.pathOrder ?? 99))
}

export function getWorkflowById(workflowId: TutorialWorkflowId): TutorialScenario | undefined {
  return TUTORIAL_WORKFLOWS.find((w) => w.workflowId === workflowId)
}

export function listCoreWorkflowIds(): TutorialWorkflowId[] {
  return [
    "positioning-content",
    "dh-oral",
    "image-video",
    "mashup",
    "promo",
    "geo-growth",
  ]
}
